# Generated by Django 4.1.3 on 2022-12-11 18:39

from django.db import migrations, models
import django.db.models.deletion
import drawingdoc.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingdoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingname',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drawingdoc.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drawing',
            name='design_stage',
            field=models.CharField(choices=[('PW', 'Projekt wykonawczy'), ('PB', 'Projekt budowlany'), ('PK', 'Projekt koncepcyjny')], default='PW', max_length=3),
        ),
        migrations.AlterField(
            model_name='drawingfile',
            name='file_field',
            field=models.FileField(upload_to=drawingdoc.models.directory_path),
        ),
    ]
