# Generated by Django 4.1.3 on 2023-02-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawingdoc', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawinguser',
            name='status',
            field=models.CharField(blank=True, choices=[(None, ' '), ('accepted', 'accepted'), ('to correct', 'to correct'), ('uploaded', 'uploaded')], max_length=100),
        ),
    ]
