# Generated by Django 4.1.3 on 2023-02-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawingdoc', '0003_alter_drawinguser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(unique=True)),
                ('duration', models.DateField()),
                ('date_start', models.DateField()),
                ('date_finish', models.DateField()),
                ('predecessors', models.CharField(max_length=100)),
                ('outline_level', models.IntegerField(unique=True)),
                ('notes', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawingdoc.project')),
            ],
        ),
    ]
