# Generated by Django 4.1.3 on 2023-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
