# Generated by Django 4.1.3 on 2023-02-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='outline_level',
            field=models.IntegerField(),
        ),
    ]
