# Generated by Django 4.1.3 on 2023-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_outline_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='predecessors',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
