# Generated by Django 4.1.3 on 2023-02-11 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_duration_schedule_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='outline_level',
        ),
    ]
