# Generated by Django 4.1.3 on 2023-02-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_outline_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='notes',
        ),
    ]
